name: srntt_sisr_only
gpus: [0]
output_dir: log

model:
  generator: srntt
  n_resblocks: 16

data:
  input_size: [80, 80]
  scale: 4

  train:
    name: DIV2K
    batch_size: 25
    input_dir: /home/zwj/Data/RefSR/DIV2K_small/input
    ref_dir: /home/zwj/Data/RefSR/DIV2K_small/ref
    map_dir: /home/zwj/Data/RefSR/DIV2K_small/map_321
    n_workers: 8

  val:
    name: SET5
    input_dir: /home/zwj/Data/benchmark/Set5
    ref_dir: /home/zwj/Data/benchmark/Set5
    n_workers: 4

schedule:
  use_weights: true
  concat: true
  lr: 1e-4
  optimizer: Adam
  beta1: 0.9
  reconst_loss: L1
  num_epochs: 10
